import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased h-screen bg-[#3a6b35] overflow-x-hidden`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
